import {
    Mainnet,
    Goerli,
    Kovan,
    Rinkeby,
    Ropsten,
    BSC,
    Cronos,
    xDai,
    Polygon,
    Moonriver,
    Moonbeam,
    Mumbai,
    OasisEmerald,
    Harmony,
    Theta,
    Palm,
    Fantom,
    Avalanche,
    Songbird,
    Velas
} from "@usedapp/core";

export const SUPPORTED_CHAINS = [
    Mainnet,
    Goerli,
    Kovan,
    Rinkeby,
    Ropsten,
    BSC,
    Cronos,
    xDai,
    Polygon,
    Moonriver,
    Moonbeam,
    Mumbai,
    OasisEmerald,
    Harmony,
    Theta,
    Palm,
    Fantom,
    Avalanche,
    Songbird,
    Velas
]

export const CHAIN_ICONS = {
    [Mainnet.chainId]: "/images/mainnet-network.jpg",
    [Goerli.chainId]: "/images/goerli-network.jpg",
    [Kovan.chainId]: "/images/kovan-network.jpg",
    [Rinkeby.chainId]: "/images/rinkeby-network.jpg",
    [Ropsten.chainId]: "/images/ropsten-network.jpg",
    [BSC.chainId]: "/images/bsc-network.jpg",
    [Cronos.chainId]: "/images/cronos-network.jpg",
    [xDai.chainId]: "/images/xdai-network.jpg",
    [Polygon.chainId]: "/images/polygon-network.jpg",
    [Moonriver.chainId]: "/images/moonriver-network.jpg",
    [Moonbeam.chainId]: "/images/moonbeam-network.jpg",
    [Mumbai.chainId]: "/images/mumbai-network.jpg",
    [OasisEmerald.chainId]: "/images/oassis-network.jpg",
    [Harmony.chainId]: "/images/harmonyone-network.jpg",
    [Theta.chainId]: "/images/theta-network.jpg",
    [Palm.chainId]: "/images/palm-network.jpg",
    [Fantom.chainId]: "/images/fantom-network.jpg",
    [Avalanche.chainId]: "/images/avalanche-network.jpg",
    [Songbird.chainId]: "/images/songbird-network.jpg",
    [Velas.chainId]: "/images/velas-network.jpg",
}

export const RPC_URLS = {
    [Mainnet.chainId]: "https://mainnet.infura.io/v3/${INFURA_API_KEY}",
    [Goerli.chainId]: "https://goerli.infura.io/v3/${INFURA_API_KEY}",
    [Kovan.chainId]: "https://kovan.poa.network",
    [Rinkeby.chainId]: "https://rinkeby.infura.io/v3/${INFURA_API_KEY}",
    [Ropsten.chainId]: "https://ropsten.infura.io/v3/${INFURA_API_KEY}",
    [BSC.chainId]: "https://bsc-dataseed2.defibit.io",
    [Cronos.chainId]: "https://evm.cronos.org",
    [xDai.chainId]: "https://rpc.gnosischain.com",
    [Polygon.chainId]: "https://rpc-mainnet.matic.network",
    [Moonriver.chainId]: "https://rpc.api.moonriver.moonbeam.network",
    [Moonbeam.chainId]: "https://rpc.api.moonbeam.network",
    [Mumbai.chainId]: "https://matic-mumbai.chainstacklabs.com",
    [OasisEmerald.chainId]: "https://emerald.oasis.dev",
    [Harmony.chainId]: "https://api.harmony.one",
    [Theta.chainId]: "https://eth-rpc-api.thetatoken.org/rpc",
    [Palm.chainId]: "https://palm-mainnet.infura.io/v3/{INFURA_API_KEY}",
    [Fantom.chainId]: "https://rpc.ftm.tools",
    [Avalanche.chainId]: "https://api.avax.network/ext/bc/C/rpc",
    [Songbird.chainId]: "https://songbird.towolabs.com/rpc",
    [Velas.chainId]: "https://evmexplorer.velas.com/rpc",
}